behaviors:
  Predator:
    trainer_type: ppo
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-3
      learning_rate_schedule: linear
      # use_curiosity: true

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encoder_type: simple
      normalize: false
      hidden_units: 64
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 1.0e6
    time_horizon: 100
    summary_freq: 10000
    keep_checkpoints: 10
    checkpoint_interval: 100000
    threaded: true
    init_path: null

    # behavior cloning
    # behavioral_cloning:
    #   demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
    #   strength: 0.5
    #   steps: 150000
    #   batch_size: 512
    #   num_epoch: 3
    #   samples_per_update: 0

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1
        gamma: 0.99

      # curiosity module
      # curiosity:
      #   strength: 0.02
      #   gamma: 0.99
      #   encoding_size: 256
      #   learning_rate: 3.0e-4
      # GAIL
      # gail:
      #   strength: 0.01
      #   gamma: 0.99
      #   encoding_size: 128
      #   demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
      #   learning_rate: 3.0e-4
      #   use_actions: false
      #   use_vail: false

    # self-play
    # self_play:
    #   window: 10
    #   play_against_latest_model_ratio: 0.5
    #   save_steps: 50000
    #   swap_steps: 2000
    #   team_change: 100000
    # use TensorFlow backend
    # framework: tensorflow

  Shooter:
    trainer_type: ppo
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-3
      learning_rate_schedule: linear
      # use_curiosity: true

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encoder_type: simple
      normalize: false
      hidden_units: 64
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 1.0e6
    time_horizon: 100
    summary_freq: 10000
    keep_checkpoints: 10
    checkpoint_interval: 100000
    threaded: true
    init_path: null

    # behavior cloning
    # behavioral_cloning:
    #   demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
    #   strength: 0.5
    #   steps: 150000
    #   batch_size: 512
    #   num_epoch: 3
    #   samples_per_update: 0

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1
        gamma: 0.99

      # curiosity module
      # curiosity:
      #   strength: 0.02
      #   gamma: 0.99
      #   encoding_size: 256
      #   learning_rate: 3.0e-4
      # GAIL
      # gail:
      #   strength: 0.01
      #   gamma: 0.99
      #   encoding_size: 128
      #   demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
      #   learning_rate: 3.0e-4
      #   use_actions: false
      #   use_vail: false

    # self-play
    # self_play:
    #   window: 10
    #   play_against_latest_model_ratio: 0.5
    #   save_steps: 50000
    #   swap_steps: 2000
    #   team_change: 100000
    # use TensorFlow backend
    # framework: tensorflow

environment_parameters:
  speed:
    curriculum:
      - name: Easy - 1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 2
        value: 1
      - name: Medium [2,5] # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 2
            max_value: 5
      - name: Hard [5,10]
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 5
            max_value: 10
      - name: Insane - 15
        value: 15
  acceleration:
    curriculum:
      - name: Easy - 8 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3
        value: 8
      - name: Medium [8,14] # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 2
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 8
            max_value: 14
      - name: Hard [14,20]
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 2
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 14
            max_value: 20
      - name: Insane - 25
        value: 25
  enemies:
    curriculum:
      - name: Easy - 5 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 5
      - name: Medium - 4 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2
          require_reset: true
        value: 4
      - name: Hard - 3
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2
          require_reset: true
        value: 3
      - name: Insane - 1
        value: 1
  spawnRange:
    curriculum:
      - name: Easy # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Predator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 5
      - name: Far # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Predator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: .2
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            max_value: 8
            min_value: 6
      - name: Medium
        completion_criteria:
          measure: reward
          behavior: Predator
          signal_smoothing: true
          min_lesson_length: 300
          threshold: .1
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            max_value: 10
            min_value: 8
      - name: Insane - 13
        value: 13
